import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/ui/container";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/ui/product-card";
import { getPublicProducts } from "@/lib/data/products";

export const metadata: Metadata = {
  title: "Regenerated by Memory Lane",
  description:
    "Every piece we sell is regenerated — selected, identified, researched, catalogued and returned to circulation. Not everything old belongs in the past.",
};

const steps = [
  {
    n: "01",
    t: "Discover",
    d: "Remarkable pieces are found before they leave circulation — the ones worth preserving.",
  },
  {
    n: "02",
    t: "Identify",
    d: "Maker, period, materials and marks are researched and recorded. What we can't verify, we don't claim.",
  },
  {
    n: "03",
    t: "Regenerate",
    d: "Cleaned, assessed honestly, photographed properly and catalogued with a full condition report.",
  },
  {
    n: "04",
    t: "Recirculate",
    d: "Priced fairly against real sold comparables and passed on to someone who'll use it again.",
  },
];

export default async function RegeneratedPage() {
  const products = await getPublicProducts();

  return (
    <>
      <section className="bg-ink text-paper ink-texture">
        <Container width="wide">
          <div className="max-w-2xl py-16 sm:py-24">
            <p className="text-2xs font-semibold uppercase tracking-[0.2em] text-accent">
              Regenerated by Memory Lane
            </p>
            <h1 className="mt-5 font-display text-4xl leading-[1.05] sm:text-5xl">
              Not everything old belongs in the past
            </h1>
            <p className="mt-5 text-lg text-paper/80">
              Thousands of beautiful, useful and historically interesting objects
              disappear from circulation every year. We find the ones worth
              preserving, give them another life, and connect them with people
              who&rsquo;ll appreciate them again.
            </p>
          </div>
        </Container>
      </section>

      <section className="py-16 sm:py-20">
        <Container width="wide">
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((s) => (
              <div key={s.n}>
                <p className="font-display text-3xl text-accent">{s.n}</p>
                <h2 className="mt-2 font-display text-xl text-ink">{s.t}</h2>
                <p className="prose-warm mt-2 text-sm">{s.d}</p>
              </div>
            ))}
          </div>
          <div className="mt-10 rounded-[var(--radius-card)] border border-paper-line bg-paper-dim p-6 text-sm sm:p-8">
            <p className="font-display text-lg text-ink">
              The Memory Lane Regenerated mark
            </p>
            <p className="prose-warm mt-2">
              A piece carrying the Regenerated mark has been selected, researched,
              catalogued and returned to circulation by Memory Lane — with an
              honest account of its condition. It&rsquo;s a mark of care, not a
              certificate of authenticity.
            </p>
          </div>
        </Container>
      </section>

      {products.length > 0 && (
        <section className="border-t border-paper-line py-16 sm:py-20">
          <Container width="wide">
            <div className="mb-8 flex items-end justify-between">
              <h2 className="font-display text-3xl text-ink">
                Regenerated &amp; available now
              </h2>
              <Link
                href="/shop"
                className="hidden text-sm text-accent-dark underline underline-offset-4 sm:block"
              >
                Shop everything
              </Link>
            </div>
            <div className="grid grid-cols-2 gap-5 md:grid-cols-3 lg:grid-cols-4">
              {products.slice(0, 8).map((p) => (
                <ProductCard
                  key={p.slug}
                  product={{
                    slug: p.slug,
                    title: p.meta_title,
                    categoryName: p.category_name,
                    askingPrice: p.asking_price,
                    currency: p.currency,
                    status: p.status,
                    photoUrl: p.photo_url,
                  }}
                />
              ))}
            </div>
            <div className="mt-10">
              <Button href="/sell" variant="secondary">
                Have something worth regenerating?
              </Button>
            </div>
          </Container>
        </section>
      )}
    </>
  );
}
